AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app-R

  Sample SAM Template for sam-app-R

  '
Globals:
  Function:
    Timeout: 30
Resources:
  SamRFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://samtestaishu/c4a91462c039e519da2c589611e5420c
      Handler: script.handler
      Runtime: provided
      Layers:
      - arn:aws:lambda:us-east-1:131329294410:layer:r-runtime-3_6_0:12
      - arn:aws:lambda:us-east-1:131329294410:layer:r-recommended-3_6_0:12
      MemorySize: 1024
      Events:
        SamR:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  SamRApi:
    Description: API Gateway endpoint URL for Prod stage for Sam Testing function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app/
  SamRFunction:
    Description: Sam Testing Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SamRFunction
      - Arn
  SamRFunctionIamRole:
    Description: Implicit IAM Role created for Sam Testing function
    Value:
      Fn::GetAtt:
      - SamRFunctionRole
      - Arn
